# Generated by Django 5.1.5 on 2025-03-29 05:33

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='病虫害名称')),
                ('description', models.TextField(blank=True, verbose_name='病虫害描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '病虫害',
                'verbose_name_plural': '病虫害',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='PlantingTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='种植技术名称')),
                ('description', models.TextField(blank=True, verbose_name='种植技术描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '种植技术',
                'verbose_name_plural': '种植技术',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='土壤名称')),
                ('ph_range', models.FloatField(max_length=10, verbose_name='pH范围')),
                ('organic_matter', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='有机质含量(%)')),
                ('description', models.TextField(verbose_name='特征描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '土壤类型',
                'verbose_name_plural': '土壤类型',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='品种名称')),
                ('scientific_name', models.CharField(blank=True, max_length=150, verbose_name='学名')),
                ('origin', models.CharField(default='中国', max_length=50, verbose_name='原产地')),
                ('growth_cycle', models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MinValueValidator(90), django.core.validators.MaxValueValidator(365)], verbose_name='生长周期(天)')),
                ('chill_requirement', models.PositiveSmallIntegerField(default=0, help_text='7.2℃以下低温累计时长', verbose_name='需冷量(小时)')),
                ('fruit_weight', models.DecimalField(decimal_places=1, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(1000)], verbose_name='平均单果重(g)')),
                ('brix', models.DecimalField(decimal_places=1, default=10, max_digits=4, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(25)], verbose_name='可溶性固形物(%)')),
                ('peel_thickness', models.DecimalField(decimal_places=1, default=0.5, max_digits=3, verbose_name='果皮厚度(mm)')),
                ('cold_tolerance', models.CharField(choices=[('high', '强'), ('medium', '中'), ('low', '弱')], default='medium', max_length=10, verbose_name='耐寒性')),
                ('drought_tolerance', models.CharField(choices=[('high', '强'), ('medium', '中'), ('low', '弱')], default='medium', max_length=10, verbose_name='耐旱性')),
                ('description', models.TextField(blank=True, verbose_name='品种描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('favorite_user', models.ManyToManyField(blank=True, related_name='favorite_varieties', to=settings.AUTH_USER_MODEL, verbose_name='收藏用户')),
                ('pest', models.ManyToManyField(blank=True, to='gannan_orange.pest', verbose_name='病虫害')),
                ('planting_tech', models.ManyToManyField(blank=True, to='gannan_orange.plantingtech', verbose_name='种植技术')),
                ('soil_preference', models.ManyToManyField(to='gannan_orange.soiltype', verbose_name='适宜土壤类型')),
            ],
            options={
                'verbose_name': '品种',
                'verbose_name_plural': '品种',
                'ordering': ['-create_time'],
            },
        ),
    ]
