# Generated by Django 5.1.5 on 2025-03-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gannan_orange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variety',
            name='soil_preference',
            field=models.ManyToManyField(blank=True, to='gannan_orange.soiltype', verbose_name='适宜土壤类型'),
        ),
    ]
