# Generated by Django 5.1.5 on 2025-03-29 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gannan_orange', '0002_alter_variety_soil_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variety',
            name='brix',
            field=models.DecimalField(decimal_places=1, default=10, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)], verbose_name='可溶性固形物(%)'),
        ),
        migrations.AlterField(
            model_name='variety',
            name='fruit_weight',
            field=models.DecimalField(decimal_places=1, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='平均单果重(g)'),
        ),
    ]
