# Generated by Django 5.1.5 on 2025-03-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gannan_orange', '0003_alter_variety_brix_alter_variety_fruit_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='pest',
            name='affected_parts',
            field=models.CharField(blank=True, help_text='如：叶片、果实、根系等', max_length=100, verbose_name='受害部位'),
        ),
        migrations.AddField(
            model_name='pest',
            name='biological_control',
            field=models.TextField(blank=True, verbose_name='生物防治'),
        ),
        migrations.AddField(
            model_name='pest',
            name='chemical_control',
            field=models.TextField(blank=True, help_text='推荐药剂及使用方法', verbose_name='化学防治'),
        ),
        migrations.AddField(
            model_name='pest',
            name='life_cycle',
            field=models.TextField(blank=True, verbose_name='生活史'),
        ),
        migrations.AddField(
            model_name='pest',
            name='occurrence_season',
            field=models.CharField(blank=True, help_text='如：春季、夏季或具体月份', max_length=50, verbose_name='发生季节'),
        ),
        migrations.AddField(
            model_name='pest',
            name='physical_control',
            field=models.TextField(blank=True, verbose_name='物理防治'),
        ),
        migrations.AddField(
            model_name='pest',
            name='prevention_methods',
            field=models.TextField(blank=True, verbose_name='预防方法'),
        ),
        migrations.AddField(
            model_name='pest',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='学名'),
        ),
        migrations.AddField(
            model_name='pest',
            name='severity',
            field=models.CharField(choices=[('mild', '轻微'), ('moderate', '中等'), ('severe', '严重'), ('devastating', '毁灭性')], default='moderate', max_length=12, verbose_name='危害程度'),
        ),
        migrations.AddField(
            model_name='pest',
            name='symptoms',
            field=models.TextField(blank=True, verbose_name='症状特征'),
        ),
        migrations.AddField(
            model_name='pest',
            name='type',
            field=models.CharField(choices=[('disease', '病害'), ('insect', '虫害'), ('mite', '螨害'), ('weed', '杂草'), ('other', '其他')], default='disease', max_length=10, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='plantingtech',
            name='applicable_season',
            field=models.CharField(choices=[('spring', '春季'), ('summer', '夏季'), ('autumn', '秋季'), ('winter', '冬季'), ('all', '全年')], default='all', max_length=10, verbose_name='适用季节'),
        ),
        migrations.AddField(
            model_name='plantingtech',
            name='category',
            field=models.CharField(choices=[('planting', '栽培管理'), ('pruning', '修剪整形'), ('fertilization', '施肥技术'), ('irrigation', '灌溉技术'), ('pest_control', '病虫害防治'), ('harvest', '采收技术'), ('storage', '贮藏保鲜'), ('other', '其他技术')], default='planting', max_length=20, verbose_name='技术类别'),
        ),
        migrations.AddField(
            model_name='plantingtech',
            name='difficulty',
            field=models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级'), ('expert', '专家')], default='intermediate', max_length=15, verbose_name='难度级别'),
        ),
        migrations.AddField(
            model_name='plantingtech',
            name='equipment_needed',
            field=models.TextField(blank=True, verbose_name='所需设备工具'),
        ),
        migrations.AddField(
            model_name='plantingtech',
            name='estimated_cost',
            field=models.CharField(blank=True, help_text='如：低/中/高或具体金额范围', max_length=50, verbose_name='预估成本'),
        ),
        migrations.AddField(
            model_name='plantingtech',
            name='expected_outcome',
            field=models.TextField(blank=True, verbose_name='预期效果'),
        ),
        migrations.AddField(
            model_name='plantingtech',
            name='labor_intensity',
            field=models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=10, verbose_name='劳动强度'),
        ),
        migrations.AddField(
            model_name='plantingtech',
            name='precautions',
            field=models.TextField(blank=True, verbose_name='注意事项'),
        ),
        migrations.AddField(
            model_name='soiltype',
            name='cation_exchange',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='阳离子交换量(cmol/kg)'),
        ),
        migrations.AddField(
            model_name='soiltype',
            name='drainage',
            field=models.CharField(choices=[('excellent', '优'), ('good', '良'), ('moderate', '中'), ('poor', '差')], default='good', max_length=10, verbose_name='排水性'),
        ),
        migrations.AddField(
            model_name='soiltype',
            name='fertility',
            field=models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='肥力'),
        ),
        migrations.AddField(
            model_name='soiltype',
            name='improvement_methods',
            field=models.TextField(blank=True, verbose_name='改良方法'),
        ),
        migrations.AddField(
            model_name='soiltype',
            name='nitrogen_content',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='氮含量(%)'),
        ),
        migrations.AddField(
            model_name='soiltype',
            name='phosphorus_content',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='磷含量(mg/kg)'),
        ),
        migrations.AddField(
            model_name='soiltype',
            name='potassium_content',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='钾含量(mg/kg)'),
        ),
        migrations.AddField(
            model_name='soiltype',
            name='suitable_crops',
            field=models.TextField(blank=True, verbose_name='适宜作物'),
        ),
        migrations.AddField(
            model_name='soiltype',
            name='texture',
            field=models.CharField(choices=[('sandy', '砂质'), ('loamy', '壤质'), ('clay', '粘质'), ('silty', '粉质'), ('peaty', '泥炭质'), ('chalky', '石灰质'), ('mixed', '混合质')], default='loamy', max_length=10, verbose_name='土壤质地'),
        ),
        migrations.AddField(
            model_name='soiltype',
            name='water_retention',
            field=models.CharField(choices=[('high', '强'), ('medium', '中'), ('low', '弱')], default='medium', max_length=10, verbose_name='保水性'),
        ),
        migrations.AddField(
            model_name='variety',
            name='acidity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='酸度(%)'),
        ),
        migrations.AddField(
            model_name='variety',
            name='altitude_range',
            field=models.CharField(blank=True, help_text='如：200-800米', max_length=50, verbose_name='适宜海拔范围(米)'),
        ),
        migrations.AddField(
            model_name='variety',
            name='annual_yield',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='平均亩产(kg)'),
        ),
        migrations.AddField(
            model_name='variety',
            name='disease_resistance',
            field=models.CharField(choices=[('high', '强'), ('medium', '中'), ('low', '弱')], default='medium', max_length=10, verbose_name='抗病性'),
        ),
        migrations.AddField(
            model_name='variety',
            name='fruit_color',
            field=models.CharField(blank=True, max_length=50, verbose_name='果皮颜色'),
        ),
        migrations.AddField(
            model_name='variety',
            name='fruit_shape',
            field=models.CharField(choices=[('round', '圆形'), ('oblate', '扁圆形'), ('oval', '椭圆形'), ('pear', '梨形'), ('irregular', '不规则形')], default='round', max_length=20, verbose_name='果实形状'),
        ),
        migrations.AddField(
            model_name='variety',
            name='harvest_season',
            field=models.CharField(blank=True, help_text='如：10-12月', max_length=50, verbose_name='采收季节'),
        ),
        migrations.AddField(
            model_name='variety',
            name='juice_content',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='果汁含量(%)'),
        ),
        migrations.AddField(
            model_name='variety',
            name='maturity_type',
            field=models.CharField(choices=[('early', '早熟'), ('mid', '中熟'), ('late', '晚熟')], default='mid', max_length=10, verbose_name='成熟类型'),
        ),
        migrations.AddField(
            model_name='variety',
            name='pollination_type',
            field=models.CharField(blank=True, help_text='如：自花授粉、虫媒授粉等', max_length=50, verbose_name='授粉类型'),
        ),
        migrations.AddField(
            model_name='variety',
            name='registration_number',
            field=models.CharField(blank=True, help_text='国家或地方品种登记编号', max_length=50, verbose_name='品种登记号'),
        ),
        migrations.AddField(
            model_name='variety',
            name='seed_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='平均种子数'),
        ),
        migrations.AddField(
            model_name='variety',
            name='shelf_life',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='保鲜期(天)'),
        ),
        migrations.AddField(
            model_name='variety',
            name='sugar_acid_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='糖酸比'),
        ),
        migrations.AddField(
            model_name='variety',
            name='tree_shape',
            field=models.CharField(blank=True, help_text='如：开心形、自然圆头形等', max_length=50, verbose_name='树形'),
        ),
        migrations.AddField(
            model_name='variety',
            name='waterlogging_tolerance',
            field=models.CharField(choices=[('high', '强'), ('medium', '中'), ('low', '弱')], default='medium', max_length=10, verbose_name='耐涝性'),
        ),
        migrations.AlterField(
            model_name='soiltype',
            name='ph_range',
            field=models.CharField(max_length=10, verbose_name='pH范围'),
        ),
    ]
