# Generated by Django 5.1.5 on 2025-03-29 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gannan_orange', '0004_pest_affected_parts_pest_biological_control_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pest',
            name='review_comment',
            field=models.TextField(blank=True, verbose_name='审核意见'),
        ),
        migrations.AddField(
            model_name='pest',
            name='review_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='pest',
            name='review_status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='pest',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_pests', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='plantingtech',
            name='review_comment',
            field=models.TextField(blank=True, verbose_name='审核意见'),
        ),
        migrations.AddField(
            model_name='plantingtech',
            name='review_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='plantingtech',
            name='review_status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='plantingtech',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_planting_techs', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='soiltype',
            name='review_comment',
            field=models.TextField(blank=True, verbose_name='审核意见'),
        ),
        migrations.AddField(
            model_name='soiltype',
            name='review_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='soiltype',
            name='review_status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='soiltype',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_soil_types', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='variety',
            name='review_comment',
            field=models.TextField(blank=True, verbose_name='审核意见'),
        ),
        migrations.AddField(
            model_name='variety',
            name='review_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='variety',
            name='review_status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='variety',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_varieties', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
    ]
