# Generated by Django 5.1.5 on 2025-03-31 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gannan_orange', '0006_reviewhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
            ],
            options={
                'verbose_name': '品种分类',
                'verbose_name_plural': '品种分类',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='variety',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='varieties', to='gannan_orange.category', verbose_name='品种分类'),
        ),
    ]
