# Generated by Django 5.1.5 on 2025-04-11 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gannan_orange', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, verbose_name='模型名称')),
                ('success_rate', models.FloatField(default=0.0, verbose_name='识别成功率')),
                ('avg_confidence', models.FloatField(default=0.0, verbose_name='平均置信度')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('avg_response_time', models.FloatField(default=0.0, verbose_name='平均响应时间(秒)')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='最后使用时间')),
            ],
            options={
                'verbose_name': '模型使用统计',
                'verbose_name_plural': '模型使用统计',
            },
        ),
        migrations.CreateModel(
            name='RecognitionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recognition_images/%Y/%m/', verbose_name='上传图片')),
                ('confidence', models.FloatField(default=0.0, verbose_name='置信度')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='识别时间')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('api_response', models.JSONField(blank=True, null=True, verbose_name='API响应')),
                ('model_used', models.CharField(blank=True, max_length=50, null=True, verbose_name='使用模型')),
                ('response_time', models.FloatField(default=0.0, verbose_name='响应时间(秒)')),
                ('result_pest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gannan_orange.pest', verbose_name='识别结果')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '识别历史',
                'verbose_name_plural': '识别历史',
                'ordering': ['-create_time'],
            },
        ),
    ]
