# Generated by Django 5.1.5 on 2025-03-31 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_qa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created_at'], 'verbose_name': '回答', 'verbose_name_plural': '回答'},
        ),
        migrations.AlterModelOptions(
            name='expertprofile',
            options={'verbose_name': '专家资料', 'verbose_name_plural': '专家资料'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': '问题', 'verbose_name_plural': '问题'},
        ),
        migrations.AddField(
            model_name='question',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_questions', to=settings.AUTH_USER_MODEL, verbose_name='指定专家'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(verbose_name='回答内容'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='回答专家'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='是否被采纳'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='accepted_answers',
            field=models.IntegerField(default=0, verbose_name='被采纳数'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='bio',
            field=models.TextField(verbose_name='专家简介'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='category',
            field=models.CharField(choices=[('planting', '种植'), ('harvesting', '收获'), ('pest_control', '病虫害防治'), ('fertilizer', '肥料'), ('irrigation', '灌溉'), ('soil', '土壤'), ('other', '其他')], default='other', max_length=20, verbose_name='专业类别'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='expertise',
            field=models.CharField(max_length=100, verbose_name='专家领域'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='是否认证'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='level',
            field=models.CharField(choices=[('beginner', '初级专家'), ('intermediate', '中级专家'), ('advanced', '高级专家'), ('master', '大师级专家')], default='beginner', max_length=20, verbose_name='专家等级'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='total_answers',
            field=models.IntegerField(default=0, verbose_name='总回答数'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_profile', to=settings.AUTH_USER_MODEL, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='认证时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='提问者'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(max_length=100, verbose_name='问题类别'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_answered',
            field=models.BooleanField(default=False, verbose_name='是否已回答'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
