# Generated by Django 5.1.5 on 2025-03-31 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_qa', '0002_alter_answer_options_alter_expertprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_follow_up',
            field=models.BooleanField(default=False, verbose_name='是否为追问'),
        ),
        migrations.AddField(
            model_name='question',
            name='parent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_questions', to='expert_qa.question', verbose_name='原问题'),
        ),
    ]
