# Generated by Django 5.1.5 on 2025-04-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_qa', '0003_question_is_follow_up_question_parent_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('planting', '种植'), ('harvesting', '收获'), ('pest_control', '病虫害防治'), ('fertilizer', '肥料'), ('irrigation', '灌溉'), ('soil', '土壤'), ('other', '其他')], default='other', max_length=20, verbose_name='问题类别'),
        ),
    ]
