# Generated by Django 5.1.5 on 2025-04-01 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_qa', '0004_alter_question_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='vote_count',
            field=models.IntegerField(default=0, verbose_name='投票数'),
        ),
        migrations.AddField(
            model_name='answer',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='voted_answers', to=settings.AUTH_USER_MODEL, verbose_name='投票'),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.CharField(blank=True, max_length=200, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='question',
            name='views',
            field=models.IntegerField(default=0, verbose_name='浏览数'),
        ),
        migrations.AddField(
            model_name='question',
            name='vote_count',
            field=models.IntegerField(default=0, verbose_name='投票数'),
        ),
        migrations.AddField(
            model_name='question',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='voted_questions', to=settings.AUTH_USER_MODEL, verbose_name='投票'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='expert_qa.question', verbose_name='问题'),
        ),
    ]
