# Generated by Django 5.1.5 on 2025-04-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_qa', '0005_answer_vote_count_answer_votes_question_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='expert_avatars/', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='职称'),
        ),
    ]
